name: meoxyvaders
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flame: ^0.9.5
  audioplayers: ^0.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/player.png
    - assets/images/enemy.png
    - assets/images/bullet.png
    - assets/images/explosion-4.png
    - assets/audio/music.mp3
    - assets/audio/explosion.mp3
    - assets/audio/miss.mp3
